### ISSUE TITLE
Document Minimum JQ Version

### ISSUE THREAD

**Issue by jbronn** [DigitalGlobe/packer-templates#2]
When trying to use this the `build.sh` script, @sputnam encountered the following error when using jq 1.3:

```
jq: error: object and object cannot be multiplied
jq: error: object and object cannot be multiplied
Failed to parse template: Error parsing JSON: unexpected end of JSON input
At line 1, column 0 (offset 0):
   1:
    ^
```

Upgrading to jq 1.5 resolved the issue.  The minimum jq version should be identified and put into the README.

**Comment by sputnam** [comment]
Documentation was updated to show min version.
